spring:
  application:
    name: LawnMower

logging:
  level:
    root: info

management:
  static:
    constants:
      job_name: mowItNowJob
      step_name: mowItNowStep
      file:
        output: output.txt